version: "3.9"

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    env_file:
      - ./.env
    volumes:
      - ./backend:/app
    ports:
      - 8080:8080
    depends_on:
      - db

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: docker/nodejs/Dockerfile
    volumes:
      - ./frontend:/src # ローカルをコンテナ内にマウント
    command: sh -c "cd react-project && yarn start" #コンテナを立ち上げたときに自動的にbuildする
    ports:
      - "3000:3000"

  db:
    container_name: db
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      TZ: ${TZ}
    volumes:
      - mysql-volume:/var/lib/mysql

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  mysql-volume: