version: "3.9"

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: docker/python/Dockerfile
    volumes:
      - ./backend:/app
    ports:
      - 8080:8080

  frontend:
    container_name: frontend
    build:
      context: .
      dockerfile: docker/nodejs/Dockerfile
    volumes:
      - ./frontend:/src # ローカルをコンテナ内にマウント
    command: sh -c "cd react-project && yarn start" #コンテナを立ち上げたときに自動的にbuildする
    ports:
      - "3000:3000"

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf